### ISSUE TITLE
please fix on rotate the screen it stops the application

### ISSUE THREAD

**Issue by a-najar** [IntruderShanky/Frisson#1]
```
        at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                               at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
                                                                               at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
                                                                               at android.graphics.Bitmap.createBitmap(Bitmap.java:739)
                                                                               at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:615)
                                                                               at com.intrusoft.library.FunkyHeader.onMeasure(FunkyHeader.java:140)
                                                                               at android.view.View.measure(View.java:18880)
                                                                               at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
                                                                               at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
                                                                               at android.view.View.measure(View.java:18880)
                                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                               at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                               at android.view.View.measure(View.java:18880)
                                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                               at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                               at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                               at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                               at android.view.View.measure(View.java:18880)
                                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                               at android.view.View.measure(View.java:18880)
                                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                               at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                               at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                               at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                               at android.view.View.measure(View.java:18880)
                                                                               at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                               at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                               at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2650)
                                                                               at android.view.View.measure(View.java:18880)
                                                                               at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2104)
                                                                               at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1220)
                                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1456)
                                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1111)
                                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6017)
                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                               at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:234)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by IntruderShanky** [comment]
Solved
